dist: trusty

sudo: required

services:
- docker

language: go

go:
- 1.9.2

go_import_path: github.com/lemonldap-ng-controller/lemonldap-ng-controller

env:
  global:
  - DOCKER=docker
  - secure: rCXRNDj7wIxukABersTdswVeNj5DxurIWCux9aUB+y2X9R/yAcnN0eACCI5qVFl/MOwFSeMjr5yNLdTzxddGGQTdG49hn4mXowWfPWlGNONUP32+1vVMAwazM8FYwsm4bYsD6G7+OE4DmnI9oKTAut0PPlgAFccZZrgojUF7VN22/DCYnR0N5/C4VB+nUJZj3u16noJ43MRWh7jYUXKjiMdTGUZxZVBllTDaVz6eCv3Vfd/a5wLoIZEbgMvjeJJ+tmtVoIlnj9/KXqNNn3zxRoltj2ckKBlPCYcrxeQIKntKNOoKlvtnTLWlk4GMzTIR/Crmu4T4wGduyIFKbyAYkA3Yw3q+nk1KqjtmmddjPcsZlWTgJKcMGVb4YThGWdjVCySqt1qjOusDNvAlgWNiITg6FiJkJjqa+MTM9fO3YvRJ+/KmN1UzJaEAyRvNO/WUTd2IwdFtadOpDqacMhBK7bPXvShm0s6m0UYoZV1THIHW5xNxHFDpok6kKZrhVsz+hAkz82CmDmPdydUS1RqNcXHG0+IGNo5mBX3g1uwEr+9oBf+TEd30kd9mOsKUxHgnYlfBqZmSyUfc/G6jhayFxYMF/Sq1/mL/GkjDAmO9oFjGd68WoMwqchmZUPM3xqljlB0Bfwj4/tG7UoD7JLvfbZZ5JWYEOu34osUTcECt3cI=
  - secure: wl02u7bTNL4JXu+Sx1edcmAA2CqGa02Nu3tA/6JKJkBjGPymRw4S7WyQSW7P2kZpb6mj0FYxCUBuIJOAUuropV2fA4SM405+s6Bcc/vjwG7o5G2EVk7e1t497LUmu3OK2MDQREKonG8sg7QtC389Ggn1vYVyRrrGyFPHEW4VCXeDxIKXCSxKXjh2Bt1oHoyM3FR23MtFTPgwcWTfmquEcQHT+TEPoj45JhpX+yBscv9jJ8tZCiH52zFpffRG7LSUUaJGLmEChdx6pgc3XHT1DSMCjYGhcaoi027quY7TbPAfWoxfJIBO1uRlRDJ1XI65vjZSdpKh7QfzZa1xZSWWlDEjCwgWAn+5Bp6W7rtYAbCK4NJBcqZIC7M4WCwoQ6ZLvKdAeVFzsA7zO0FrNGub4BDlEdMdrAZCONuZ3ENw4vI6OCOQ8qz9TOA4H46zsf1j4hs7jUEyKY/40peZGEfnby54fd8OOltE9vHbLLYZPw8oorg7gkQ3Aj11SZsW/AraZOIZmi+dBbhj1qYyDjwI7GsCv1rNhx0oknJpRNN9dWRzNMzUtu7Th0zC0IHKIDk/2HBr0BUHAawPXvpZX9LVcsGJDru1YjP0EWIPk4BlJYieti71+Jpe9SU651eyRZ0ZePlsWCwbxzvitVGIOkeKlxsZOcMHB1Ba4uCAZFOgg/I=
  matrix:
  - ARCH=amd64
  - ARCH=arm
  - ARCH=arm64
  - ARCH=ppc64le
  - ARCH=s390x

stages:
- Static Check
- Build

jobs:
  include:
  - stage: Static Check
    env:
    - ARCH=amd64
    install:
    - go get github.com/golang/lint/golint
    script:
    - make verify-all

stage: Build
install:
- go get -t -v ./...
script:
- make sub-container-$ARCH
after_success:
- if [ "$TRAVIS_REPO_SLUG" == "lemonldap-ng-controller/lemonldap-ng-controller" -a "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == false ]; then
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  make sub-push-$ARCH;
  fi
