kind: ConfigMap
apiVersion: v1
metadata:
  name: lemonldap-ng-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  # SSO Cookie
  domain: example.org
  cookieName: lemonldap
  securedCookie: "0" # 0=unsecuredCookie, 1=securedCookie, 2=doubleCookie, 3=doubleCookieForSingleSession
  # cda: "1" # for Cross domain authentication

  # Portal URL
  portal: http://auth.example.org/
  mailUrl: http://auth.example.org/mail.pl
  registerUrl: http://auth.example.org/register.pl
  # https: "1" # recommended, to force HTTPs

  # Authentification, user and password backends
  # authentication: LDAP # Default Demo
  # userDB: LDAP # Default Demo
  # passwordDB: LDAP # Default Demo
  # ldapServer: ldap://ldap.example.org
  # ldapBase: dc=example,dc=org

  # Session database
  # globalStorage: Apache::Session::Browseable::Postgres # Default Apache::Session::File
  # globalStorageOptions.yaml: |
  #   DataSource: dbi:Pg:dbname=sessions;host=10.2.3.1
  #   UserName: lemonldapng
  #   Password: mysuperpassword
  #   TableName: sessions
  #   Commit: "1"
  #   Index: _whatToTrace ipAddr

  # Portal Menu
  applicationList.yaml: |
    "2administration":
      type: category
      catname: "Administration"
      "manager":
        type: application
        options:
          description: "Configure LemonLDAP::NG WebSSO"
          display: auto
          logo: "configure.png"
          name: "WebSSO Manager"
          uri: "http://manager.example.org/manager.html"
      "notifications":
        type: application
        options:
          description: "Explore WebSSO notifications"
          display: auto
          logo: "database.png"
          name: "Notifications explorer"
          uri: "http://manager.example.org/notifications.html"
      "sessions":
        type: application
        options:
          description: "Explore WebSSO sessions"
          display: auto
          logo: "database.png"
          name: "Sessions explorer"
          uri: "http://manager.example.org/sessions.html"
    "3documentation":
      type: category
      catname: "Documentation"
      "localdoc":
        type: application
        options:
          description: "Documentation supplied with LemonLDAP::NG"
          display: on
          logo: "help.png"
          name: "Local documentation"
          uri: "http://manager.example.org/doc/"
      "officialwebsite":
        type: application
        options:
          description: "Official LemonLDAP::NG Website"
          display: on
          logo: "network.png"
          name: "Offical Website"
          uri: "http://lemonldap-ng.org/"
